### ISSUE TITLE
Adding support for @dding accounts

### ISSUE THREAD

**Issue by jaredsburrows** [546200350/TikTokUploder#1]
Can you add support for being able to "tag" other accounts?

**Comment by 546200350** [comment]
> Can you add support for being able to "tag" other accounts?

ok, i will plan it

**Comment by jaredsburrows** [comment]
@546200350 Is this now supported? You can tag accounts via `@jaredsburrows`?

**Comment by 546200350** [comment]
@jaredsburrows 
update the latest script， i have add this feature

**Comment by jaredsburrows** [comment]
@546200350 Thank you!
