### ISSUE TITLE
Mention User

### ISSUE THREAD

**Issue by stevesajeev1** [546200350/TikTokUploder#12]
Hello, is it possible to mention a user when you upload a video?

**Comment by 546200350** [comment]
Well... not at the moment.
I`ll plant it.
you can also add yourself. it is the same to add tag.

**Comment by stevesajeev1** [comment]
I see in the code that the hashtag data is created through
```py
text_extra.append({"start":len(title)-len(verified_tag)-1,"end":len(title),"user_id":"","type":1,"hashtag_name":verified_tag})
```
and is posted to the url https://us.tiktok.com/api/v1/web/project/post/?aid=1988.

Unfortunately, I was unable to find any documentation for how the data should be formatted for posting to the URL, so I am unsure how to mention the user.

I assume that the `type` and `hashtag_name` fields need to be changed in order to indicate its a mention, not a hashtag.
```py
{"start":len(title)-len(verified_tag)-1,"end":len(title),"user_id":"","type":1,"hashtag_name":verified_tag}
```

How would I go on doing so? Could you provide the needed code?

**Comment by 546200350** [comment]
@stevesajeev1 
update the latest script， i have add this feature
