### ISSUE TITLE
Server currently unavailable 

### ISSUE THREAD

**Issue by TheTTCoder** [546200350/TikTokUploder#15]
It has been a few days since I am using the upload.py script, and I have the same issue every time I try to run it on a different device than my laptop. For instant I always get this error when I try running it on my raspberry pi:
```
[-] An error occured while reaching https://www.tiktok.com/api/v1/web/project/post/?aid=1988
r = <Response [200]>
r.content = b'{"status_code":4,"status_msg":"Server is currently unavailable. Please try again later.","log_pb":{"impr_id":"20230419125536859ED03C61F227194B99"}}
```

**Comment by UnMars** [comment]
Everything works fine for uploading on my side? Have you tried switching to another connection / IP, or another video to upload?

**Comment by 546200350** [comment]
> It has been a few days since I am using the upload.py script, and I have the same issue every time I try to run it on a different device than my laptop. For instant I always get this error when I try running it on my raspberry pi:
> 
> ```
> [-] An error occured while reaching https://www.tiktok.com/api/v1/web/project/post/?aid=1988
> r = <Response [200]>
> r.content = b'{"status_code":4,"status_msg":"Server is currently unavailable. Please try again later.","log_pb":{"impr_id":"20230419125536859ED03C61F227194B99"}}
> ```

mabe you can login in on your laptop, then try use this script again

**Comment by SkrowZzZ** [comment]
I also get something similar like this: ============开始上传视频===========
/home/skrowzzz/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'tos-gcpgb.tiktokcdn.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
============视频上传成功===========
[-] An error occured while reaching https://www.tiktok.com/api/v1/web/project/post/?aid=1988
r = <Response [403]>
r.content = b'<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "&#47;api&#47;v1&#47;web&#47;project&#47;post&#47;&#63;aid&#61;1988" on this server.<P>\nReference&#32;&#35;18&#46;9d551060&#46;1682390527&#46;51431852\n</BODY>\n</HTML>\n'
============发布失败===========
[-] An error occured while reaching https://www.tiktok.com/api/v1/web/project/post/?aid=1988
r = <Response [403]>
r.content = b'<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "&#47;api&#47;v1&#47;web&#47;project&#47;post&#47;&#63;aid&#61;1988" on this server.<P>\nReference&#32;&#35;18&#46;9d551060&#46;1682390527&#46;51431852\n</BODY>\n</HTML>\n'

**Comment by 546200350** [comment]
Try to replace the domain www with us

**Comment by ViktorKravtsov** [comment]
> Try to replace the domain www with us

than this error: {"status_code":8,"status_msg":"Login expired","log_pb":{"impr_id":"20230429084743ED83464FC75B83DE1B22"}}

**Comment by UnMars** [comment]
@ViktorKravtsov Try changing your sessionid

**Comment by ViktorKravtsov** [comment]
Does not help. When I try to post to www. getting error:
{"status_code":4,"status_msg":"Server is currently unavailable. Please try again later.","log_pb":{"impr_id":"202304290911064EAEE51B813AE29B1309"}}

When to us.tiktok.com (and change header Host), returns the same error

**Comment by 546200350** [comment]
it seem like being limit by tiktook

**Comment by ErinTomorri** [comment]
you gotta change the cookies when you switch computer, I had the same error and that what the fix was.
