### ISSUE TITLE
Detection by TikTok

### ISSUE THREAD

**Issue by UnMars** [546200350/TikTokUploder#18]
Whenever I post with this tool on TikTok, my video gets 0 views (stuck in fantom mode), whatever the video, whatever the account.
(I also tested with some apps that allow to post automatically and they also got stuck on 0 views.)
Am I the only one who doesn't have view when I use this tool?

I think Tiktok has some verification that you're using the Tiktok app/website and not just the API.
Maybe try to replicate some requests that are made like these ones.
![image](https://user-images.githubusercontent.com/54448435/235294498-065c0c65-b6aa-492d-818d-d3835bca6407.png)

Here's a guy that I found on GitHub who explored a bit the Tiktok API: https://github.com/xtekky?language=&page=1&q=Tiktok&sort=stargazers&tab=repositories&type=source . 
Maybe we will find something interesting to improve our uploader.

**Comment by 546200350** [comment]
all the api this script use is based on TikTok Website.
this is account, all the videos upload by this script
![image](https://user-images.githubusercontent.com/16091917/235353572-507749a0-5d28-4e68-9c72-6f2a008b6739.png)

**Comment by bilalazza** [comment]
me too i tested the script but the videos gets 0 vues im asking if i can use proxy or i must every time change the rdp where im hosting the script or there is anything i must do it like undetectable browser...

**Comment by UnMars** [comment]
> all the api this script use is based on TikTok Website. this is account, all the videos upload by this script ![image](https://user-images.githubusercontent.com/16091917/235353572-507749a0-5d28-4e68-9c72-6f2a008b6739.png)

Oh okay, amazing for you! Do you use any IP or MAC adress modification before launching the script ? Or you just launch it normally like any script with your home internet connexion ? Or maybe the account that you're using, is it aged ?
We are having the same problem with @bilalazza and you don't have it @546200350 so it must have a solution 😄

**Comment by bilalazza** [comment]
i want run it into another rdp but i get this error 
user_id = r.json()["data"]["user_id_str"]
KeyError: 'user_id_str'

can you please advice me . i look into the folder there is no json file  what can i do please

**Comment by UnMars** [comment]
Update : 
As @546200350 is in Chengu (China) he used the singapore server to upload. Whereas I'm in France, so I did set up a proxy with [Charles](https://www.charlesproxy.com/documentation/) for my smartphone to see which server i'm using when on Tiktok. 
As result I found this url : tnc16-platform-useast1a.tiktokv.com . 
So for the uploader I changed all the `url = "https://vod-ap-singapore-1.bytevcloudapi.com/"` by 
`url = "https://vod-us-east-1.bytevcloudapi.com/"` (and some changes in the AWS signature function) and I it managed to upload.
I'll keep you updated if this works or still locked with 0 views.

**Comment by ViktorKravtsov** [comment]
@UnMars did the same, but still getting 0 views if video uploaded by tool

**Comment by UnMars** [comment]
@ViktorKravtsov Any solutions found ?

**Comment by ViktorKravtsov** [comment]
@UnMars no :(

**Comment by TheTTCoder** [comment]
> Update :
> As @546200350 is in Chengu (China) he used the singapore server to upload. Whereas I'm in France, so I did set up a proxy with [Charles](https://www.charlesproxy.com/documentation/) for my smartphone to see which server i'm using when on Tiktok.
> As result I found this url : tnc16-platform-useast1a.tiktokv.com .
> So for the uploader I changed all the `url = "https://vod-ap-singapore-1.bytevcloudapi.com/"` by
> `url = "https://vod-us-east-1.bytevcloudapi.com/"` (and some changes in the AWS signature function) and I it managed to upload.
> I'll keep you updated if this works or still locked with 0 views.

Are your modifications open sourced?

**Comment by UnMars** [comment]
> > Update :
> > As @546200350 is in Chengu (China) he used the singapore server to upload. Whereas I'm in France, so I did set up a proxy with [Charles](https://www.charlesproxy.com/documentation/) for my smartphone to see which server i'm using when on Tiktok.
> > As result I found this url : tnc16-platform-useast1a.tiktokv.com .
> > So for the uploader I changed all the `url = "https://vod-ap-singapore-1.bytevcloudapi.com/"` by
> > `url = "https://vod-us-east-1.bytevcloudapi.com/"` (and some changes in the AWS signature function) and I it managed to upload.
> > I'll keep you updated if this works or still locked with 0 views.
> 
> Are your modifications open sourced?

Yes I mean I just replace the server url everywhere in the code as I said. If you have any solutions, I take it 😄

**Comment by TheTTCoder** [comment]
> > > Update :
> > > As @546200350 is in Chengu (China) he used the singapore server to upload. Whereas I'm in France, so I did set up a proxy with [Charles](https://www.charlesproxy.com/documentation/) for my smartphone to see which server i'm using when on Tiktok.
> > > As result I found this url : tnc16-platform-useast1a.tiktokv.com .
> > > So for the uploader I changed all the `url = "https://vod-ap-singapore-1.bytevcloudapi.com/"` by
> > > `url = "https://vod-us-east-1.bytevcloudapi.com/"` (and some changes in the AWS signature function) and I it managed to upload.
> > > I'll keep you updated if this works or still locked with 0 views.
> > 
> > 
> > Are your modifications open sourced?
> 
> Yes I mean I just replace the server url everywhere in the code as I said. If you have any solutions, I take it 😄

Do you have a discord so we can discuss easily?

**Comment by UnMars** [comment]
> > > > Update :
> > > > As @546200350 is in Chengu (China) he used the singapore server to upload. Whereas I'm in France, so I did set up a proxy with [Charles](https://www.charlesproxy.com/documentation/) for my smartphone to see which server i'm using when on Tiktok.
> > > > As result I found this url : tnc16-platform-useast1a.tiktokv.com .
> > > > So for the uploader I changed all the `url = "https://vod-ap-singapore-1.bytevcloudapi.com/"` by
> > > > `url = "https://vod-us-east-1.bytevcloudapi.com/"` (and some changes in the AWS signature function) and I it managed to upload.
> > > > I'll keep you updated if this works or still locked with 0 views.
> > > 
> > > 
> > > Are your modifications open sourced?
> > 
> > 
> > Yes I mean I just replace the server url everywhere in the code as I said. If you have any solutions, I take it 😄
> 
> Do you have a discord so we can discuss easily?

Here's UnMars#2668

**Comment by TheTTCoder** [comment]
I get between 70k and 200k views a day with this, so I don’t think there’s any detection by tiktok tbh

**Comment by ViktorKravtsov** [comment]
@TheTTCoder are you from China? Or you modified this script somehow?

**Comment by TheTTCoder** [comment]
> @TheTTCoder are you from China? Or you modified this script somehow?

I’m from France
