### ISSUE TITLE
 tempInfo Error when running the code

### ISSUE THREAD

**Issue by bilalazza** [546200350/TikTokUploder#19]
i there thanks for your work that great script ! 
im asking when i run the command i get this error 
 tempInfo = r.json()['project'] 
 and keyerror = 'project'

is there any json file i must create or downloading it ?

**Comment by UnMars** [comment]
r.json() is the dict returned line 25 in uploader.py of the GET request made line 17 which begin the upload process.
No any external json or nothing, it must be a connection problem or account problem.
Try to print r.json() to see what the request returned

**Comment by bilalazza** [comment]
i get this error File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ViktorKravtsov** [comment]
> i there thanks for your work that great script ! im asking when i run the command i get this error tempInfo = r.json()['project'] and keyerror = 'project'
> 
> is there any json file i must create or downloading it ?

@bilalazza change us.tiktok to www.tiktok

**Comment by bilalazza** [comment]
i did it but always the same error . im running it on rdp is there any require steps that can i do ?

**Comment by 546200350** [comment]
make sure the sessionID is correct.

**Comment by pongo9** [comment]
i got same issue, 
keyerror = 'project'

json response : {'status_code': 8, 'status_msg': 'Login expired', 'log_pb': {'impr_id': '....'}}
trying to relog then change session id didnt work

**Comment by Victor-Dlt** [comment]
Fixed with the last PR!

**Comment by davidliaos** [comment]
> Fixed with the last PR!

Getting this same error after new PR, any ideas?

**Comment by 546200350** [comment]
sorry, there is a mistake.  try use the latest script

**Comment by 546200350** [comment]
it`s ok in my machine.
<img width="694" alt="image" src="https://github.com/546200350/TikTokUploder/assets/16091917/f94ed917-7287-465f-8f13-58691868425e">

**Comment by davidliaos** [comment]
> it`s ok in my machine. <img alt="image" width="694" src="https://user-images.githubusercontent.com/16091917/237863179-f94ed917-7287-465f-8f13-58691868425e.png">

new release works, still had to do "www" instead of "us" thanks!

**Comment by matheusfterra** [comment]
In machine here works, but on VPS in container, occur the error. Some idea to fix, please?
