### ISSUE TITLE
Video Uploaded successfully, but it does not appear in profile

### ISSUE THREAD

**Issue by ViktorKravtsov** [546200350/TikTokUploder#20]
After all procedures I am getting string:
`{"status_code":0,"status_msg":"success","info":{"projectID":"86*****87","version":1,"type":1,"status":0},"extra":{"now":1682881881000,"fatal_item_ids":[],"logid":"2023043********8"},"log_pb":{"impr_id":"202304301*******8"}}`

but video does not appear in my profile.

Could you please tell me, what I am doing wrong?

P.S. Im using polish proxy. without proxy same happens

**Comment by ViktorKravtsov** [comment]
@546200350 could you please show example of response  after posting data to  `https://www.tiktok.com/api/v1/web/project/post/`

**Comment by 546200350** [comment]
make sure the sessionID is correct
