### ISSUE TITLE
KeyError: 'project' today

### ISSUE THREAD

**Issue by leonidussaks** [546200350/TikTokUploder#21]
Everything was fine, but today I ran into a problem:

```
    tempInfo = r.json()['project']
KeyError: 'project'
```

I know about the 'us->www' error and yestarday its work fine...
does anyone have this error? if not, I will look at my side

**Comment by leonidussaks** [comment]
oh, the error is related to something else

`{'status_code': 5, 'status_msg': 'Invalid parameters', 'log_pb': {'impr_id': '20230506105247D3CC28C7DBBFFF0B7232'}}`

**Comment by TheTTCoder** [comment]
I have the same issue

**Comment by stevesajeev1** [comment]
I am getting this issue as well.

**Comment by TenViki** [comment]
Same issue here

**Comment by TheTTCoder** [comment]
Yup, @546200350, any idea on how to fix it?

**Comment by TheTTCoder** [comment]
Ok guys I’ve found how to fix

**Comment by Victor-Dlt** [comment]
Made a PR to fix it

**Comment by 546200350** [comment]
> Made a PR to fix it

the website is change, add the new query creation_id.
thansk!

**Comment by EricZheng** [comment]
the committed code doesn't work still, same KeyError: 'project'

**Comment by cybr-dev** [comment]
same error
