### ISSUE TITLE
？

### ISSUE THREAD

**Issue by vinycoco** [546200350/TikTokUploder#25]
老哥你是不是少些了一个符号
![image](https://github.com/546200350/TikTokUploder/assets/47547286/c7fdaacf-be22-465e-951f-f94dec60127c)

**Comment by 546200350** [comment]
。。。。直接合并的别人的PR

**Comment by 546200350** [comment]
你确定是我少写了？

**Comment by 546200350** [comment]
> 老哥你是不是少些了一个符号 ![image](https://user-images.githubusercontent.com/47547286/237641722-c7fdaacf-be22-465e-951f-f94dec60127c.png)

sorry, 我的错
