### ISSUE TITLE
I can't found the "project" key

### ISSUE THREAD

**Issue by Toufiix** [546200350/TikTokUploder#26]
Hi,

I have this error : 
`  File "c:\Users\benja\Desktop\tiktok bot\auto-uploder\TikTokUploder-main\uploader.py", line 26, in uploadVideo                                                                                                           eo
    tempInfo = r.json()['project']
KeyError: 'project'`

Because the 'r' variable only contains : 
`{"status_code":0,"status_msg":"url doesn't match","log_pb":{"impr_id":"202305171653389A43C48F8C2C771378CF"}}`

I would know how can I solve this issue.
(Sorry for my english I'm French)

Thanks :)

**Comment by hzpapaz** [comment]
Same error here.

**Comment by devopjj** [comment]
> Hi,
> 
> I have this error : ` File "c:\Users\benja\Desktop\tiktok bot\auto-uploder\TikTokUploder-main\uploader.py", line 26, in uploadVideo eo tempInfo = r.json()['project'] KeyError: 'project'`
> 
> Because the 'r' variable only contains : `{"status_code":0,"status_msg":"url doesn't match","log_pb":{"impr_id":"202305171653389A43C48F8C2C771378CF"}}`
> 
> I would know how can I solve this issue. (Sorry for my english I'm French)
> 
> Thanks :)

Suggest you check if your session-id  expired  yet? Renew the session-id and repalce with the new one. I think it will work well.

**Comment by hzpapaz** [comment]
> > Hi,
> > I have this error : ` File "c:\Users\benja\Desktop\tiktok bot\auto-uploder\TikTokUploder-main\uploader.py", line 26, in uploadVideo eo tempInfo = r.json()['project'] KeyError: 'project'`
> > Because the 'r' variable only contains : `{"status_code":0,"status_msg":"url doesn't match","log_pb":{"impr_id":"202305171653389A43C48F8C2C771378CF"}}`
> > I would know how can I solve this issue. (Sorry for my english I'm French)
> > Thanks :)
> 
> Suggest you check if your session-id expired yet? Renew the session-id and repalce with the new one. I think it will work well.

I have the same issue and my session-id is new just got it 2 days ago

**Comment by Toufiix** [comment]
@devopjj, I tried to change my sessionID but it changes nothing. The AutoUploader is working for you ? 
Maybe the API changed ? @546200350 have you an idea ? 
Thanks for you help guys :)

**Comment by Toufiix** [comment]
Re,

Its working ! I just had to change us.tiktok.....
Thanks you guys :)

**Comment by yshial** [comment]
work?

**Comment by Toufiix** [comment]
for me yes

**Comment by Suitox93** [comment]
> Re,
> 
> Its working ! I just had to change us.tiktok..... Thanks you guys :)

Tu as changé quel ligne stp j'ai cette erreur "KeyError: 'project'" je sais pas quoi faire. je sais que ca viens du fait que en europe on peux pas se connecter au us je crois?
