### ISSUE TITLE
Login expired

### ISSUE THREAD

**Issue by NamerPolice** [546200350/TikTokUploder#28]
[-] An error occured while reaching https://us.tiktok.com/api/v1/web/project/post/?aid=1988
r = <Response [200]>
r.content = b'{"log_pb":{"impr_id":"2023052012492532CEE93A76E76F5AE521"},"status_code":8,"status_msg":"Login expired"}'

how to fix this?

**Comment by 546200350** [comment]
try login in the tiktok website, get the new sessionId

**Comment by NamerPolice** [comment]
> try login in the tiktok website, get the new sessionId
how many times I tried to change it, but it still does not work
[-] An error occured while reaching https://us.tiktok.com/api/v1/web/project/post/?aid=1988
r = <Response [200]>
r.content = b'{"status_code":8,"status_msg":"Login expired","log_pb":{"impr_id":"20230525071930000F6FAE89D2B70FFC13"}}'

**Comment by usamaehsan** [comment]
@NamerPolice are you able to solve this issue? 

My session id is working on browser but not in script
