### ISSUE TITLE
Upload a video as private

### ISSUE THREAD

**Issue by MiguelRodriguezR** [546200350/TikTokUploder#29]
is there any option to upload the video as private ?

**Comment by NamerPolice** [comment]
does it work for you at all?

**Comment by 546200350** [comment]
https://github.com/546200350/TikTokUploder/blob/f15f8f63204d3a52787e1999f949761abb19dcc3/uploader.py#LL54C5-L54C20
change to 1

**Comment by MiguelRodriguezR** [comment]
Thanks @546200350 you saved me a lot of time, you are the best!

**Comment by 546200350** [comment]
> Thanks @546200350 you saved me a lot of time, you are the best!

tks, If you found it helpful, please give me a little star
