### ISSUE TITLE
KeyError: 'project'

### ISSUE THREAD

**Issue by jaredsburrows** [546200350/TikTokUploder#3]
I believe the end point has changed or was json has changed:

## Command:
`$ python3 uploader.py -i SESSION_ID -t "Title" -p "video.mp4"`

## Output:
```
Traceback (most recent call last):
  File "/Users/<>/repo/TikTokUploder/uploader.py", line 112, in <module>
    uploadVideo(args.session_id, args.path, args.title, args.tags)
  File "/Users/<>/repo/TikTokUploder/uploader.py", line 25, in uploadVideo
    tempInfo = r.json()['project']
KeyError: 'project'
```

**Comment by fabioselau077** [comment]
Believe the endpoint has changed, now return
`{'log_pb': {'impr_id': '20230211....F'}, 'status_code': 8, 'status_msg': 'Login expired'}`

**Comment by fabioselau077** [comment]
Hello, in upload.py replace all "us." for "www." and try again.

I'm created one PR for fix this.
https://github.com/546200350/TikTokUploder/pull/4

**Comment by jaredsburrows** [comment]
@fabioselau077 Thanks. It works.

**Comment by 546200350** [comment]
Thanks, mybe it`s different for different country

**Comment by 546200350** [comment]
i have just revert, the domain is different from different country.
you can open the website network pan to find the correct domain
