### ISSUE TITLE
Keep receiving this error on us. and www.

### ISSUE THREAD

**Issue by seed1337** [546200350/TikTokUploder#34]
[-] An error occurred while reaching https://www.tiktok.com/api/v1/web/project/create/?creation_id=gxYkhL6dPsIUs73ab6CPx&type=1&aid=1988
[-] Please try to change the --url_server argument to the adapted prefix for your account

**Comment by 546200350** [comment]
maybe you need debug and show me the error response

**Comment by matheusfterra** [comment]
@546200350 hi, locally works perfect to me. But running in container in Europen VPS, occur this error, can help me, please?

**Comment by 546200350** [comment]
#37

**Comment by usamaehsan** [comment]
> @546200350 hi, locally works perfect to me. But running in container in Europen VPS, occur this error, can help me, please?

I am facing same issue, have you found any solution?
