### ISSUE TITLE
New parameters

### ISSUE THREAD

**Issue by ViktorKravtsov** [546200350/TikTokUploder#36]
Yesterday, my videos has stopped to upload. After some debugging, I have notised that we need to provide some "htc6j8njvn-" params when sending request to "/v1/web/project/post/?aid=1988". Any ideas how to generate them?

**Comment by MrUnreal** [comment]
What worked for me was to also include X-Akamai-req id, the above comes from initial request to upload

**Comment by loxeyer** [comment]
Htc6j8njvn-A:
otMdXTFsPqyV5VOIEi5Q70Hz9KIRIzSyzKazJ_tXyVcJVqVNAbO2JvxGVCOZ8StRP4Qi8YretiQazK6fTHyQwYfbmopfukKBFnZkvnrFXNrFpx0joBQkbjbejZJnOGyvsaeGDAJcm3CR2F1YZBnxRk_=dGlQu-Lq89qnai-b2Qm2pwUSiuPhB_N9owCj-jQ8csDiPpZ9x4JHKWW=dwW_vpd9y2NdXpX9Z9cxCKXb8RixCDqNJLoWa1QKdUnXpZULv7zMqo8KjNGYBtEn7xFSlBGsX7cppLFssD-mU-4QiNGcXp4Z1NYt8m8VmL0XwNyr2vaCa=Tsv5ivAbxzKKlj0532a6uFIvuGRfrsnFj5L4y0EINIPFHVSI9QdL8vdHvrB1VMjXMbNwkoZXWx5xaD8=I2KWAJLsiikFLYzvHGOAe3rREZLYUVdvxt_5woBZ9ySHY_iIed7Yij9zilMuSIl9LVxmQt-ncHB1YSA9__76G-z9KYNOuizIfFCwmRNTo8hCsTi=atO_hFXc3-jvKPyTNEhlOlx-=53VQQh82uQUHe6=7bezrOnO2kwjW8QRTzQCH5nbe5C9ZRx8C6oCUkyv-bV7fh02K5QNPEuT8Uy1MAwP3BpkxPF4bn7L5QVp4SbdOjf4hOJSC369QuORA1GSnGMW5VPFQMF8LY3sbdqC-xyBIvajfe=UQEZEN9jdlKUFosrp9zKXhwvwjzvJfcJ2D3yU75hPZ1ndFNR0WUpjBNiNWXmyX9SR2frvC=2ce05W94ABKnwONYhPfDEy35ndfaxlJGaLBPqyOGNAGIy-3XlGMmvCH8OkSiWLjOjLcju=jK-Zl4vxFfWStCDmREDeYZWBw-_nncBcct9x5BHjwzBnMfQpj=xp3o_VVt5mTtSOq1oe0X_5k2tWTeXzaxBofeRMDbE72HnwkB=0MxHBsQFwSpe58nQPPwx1ws1WlcYExrdxb7sCtiXLl9hOathUWaLX3hl5fk7vs5Pe=ZFItp4QeUmrjw6kARqn7OTBOcpIdau1Ls0F=8wQ_LO6=saMZstbk==mvi0GGpL3SIHqRG3TkbHTPd-UlMj=3U-ebxMMDBS9PpiWQnfs95XmVbVWrCM83=pXjLJroCL9jwn=Q3Oet6unyk9RlaYRyDGShLeUXMEi6=PsrIdeLnsM_c6bWn7nl6iPrDqCpZbrcGSwYqHpV3kwlIvjRx6wnP78ZeAYC7cMu=nDK0xCqdRaOYQHb8FeH8S5dozyE4qBvE_=EDGrv845ljrFEzoYFhcRTXDm4XnNO8cDforSoid3xp7kT5bpRPJrwe7-Ew15S_rLWI7k=6Ol_fxzQxT_LMy1cYK3swwtu4CswPKx0ytKfuCIHlCzj13lvPQCSHtq==ELQ4Rv28jZFboUiYO_CqhW-bazDGYOGdNL3ONGXGWxGBxYwWMrmT3r4oIAlj74XErR0SamTeo=4ZU3I8Up8fY8=rpRnVh9KmNK=RVc2en13=_-K-mGcRjEHRLoTkpMnGuxxX=B7HUfYa0AVwYii_XBTlryvFp71IJNxu9xMb6tIY6Q_AK9HkYsJ6p2-ZFEV=t5UhzBaCVPK-FCUIjvxIpNsLb9k0THPuBSbeHfyK7SQdy7yrpUNH0tCf9rZ9zIu-bfR4PSTf9s_fJUY3m6mRBzHkRwfVG3BkpcfUckCTsGxWN3akWqzNnvQrDA5vcz8r3N8aCe1lbkI_qvqy4_fhBG1-RDfik3XSHrV2rUx-4EJ8yS6tyMJwjkQjNBpRn2PKyhbW84_3RQBCCwSUsTYO4VMUoG3DjThv_TZ8oOnpw=fq_klePPHOPY-JIb5505YmqmMjfy1EXNUv68KmA03C=SxZVT7pf-mNZcsnrjlqVSzmbWBW62oo8KeMBqW42yKTGJtd8RZX_eKQW4G=Olk97YcWq9nuMDjprLNPcOKWPJMz84Fv9nMFCfI7SbTHdyjSOrIJSnYuppa0iEwbj_6dB=HrM0BYLo9OTSplXnrE0Aw0LuFrpDTSR=e7mAVGAFfve6COK3RZfVA-banSklOl8GEejPEMlyI4Qm=jMaw3DPb5AH=0Xo6HM3wydtc2KTd=uuDoOTvfhn-Mljx6fKFZJ7QSEHa6C3CwJBLK9PZexlojbcZSbAHbwXSEO1YfOSHwBR1r_GNMrwHAau9UFzSRFqI9TUoUKiIFak68-opnGJU3KCe7wtxvLHAS2K=iRqCHlQr5ooPvzIrVffhbyXMm1W8ZQC-scssthtPNLIftqVGcenDyWUqxQLzo7RubjzxBG=UIMMkzy9W2AcF10WaUQjODEJOOBGGoXEkL3BIM8SQpGwb1XML7DUnKmwU8BhwtU3qFKaZClKEVtC=sfv6_B2LJBrvEj59ohi8xOE9ILLxrA3hwDZwYU8TR44uqs9VQ8cwU7qhOfs34F4Yt0xfNm846lCboEYFY89Vm4MI4IicNDayU-5QssaTQYnmfemIjVHnkzaa=4cwNQu-xYpMOiafM2S2CWXtKt-G1Xfplf=Z7OijBHT4ahOLX370Oon=vyW7yZDJVyNwa05_QBAb34KdUWAVLkNin3yi_HdMknd_LPAHS4t=PqiDF1YD-ev19DReJMVtRNAJsNVJ24rCtRnvR3bk7jvKCViIZfKcNGIGU=xT9NZ7A9BFS8-du1iTKxerb5Pz4hhAWXrE__iT=uZ-PMvXlkmxhzS4xdOXa0AoSb0kljSThy3zjk6c94PfCAWVrWV41_viK3pMlWRS1d9e1IqXU=9fWJRupULw8nBqScDi2s_EICkqpSDvv6tbPMf=NGBATyANUZtUPETl1R1IG03A5WkfIWlHTjWSlLPA78uWseo4i4yv_6AGJtdLtk1F9R1wI3uw0KJE4VjymAdIw-Yq-R7H5r7s-bh0q8T91P9DRL4n0SE2E9atynO9QqK-0xt_pO7ef1nJDmcwM9bfLjw6P1EiDUxnc-a5RRHpoQ2KWZ-EJF98lF6l3y3JW7BOhzm-ZrWpuAIdJUk05x-nWaUHwPk5GDdNnodJjaL5-9hx8TzLNqdxfe25AHOyq-s-J0kVtxkKhX4BFiJZBWsayjEe8pANtGKaOpxoQZMJDcjCzmSukUT=1J9DW65liz1rP07dfiCY9rdY1hw=Rfh==yFAIeRtXj8K7DN-I9DpIE=T6s3=3Sz_hqR-2CcyrsWAFQ6dMJADGTUKTZ=mts8QB79u-Si1LMMkfr2SdVvkxHuNlqxXv96aF_s9yDjRfG0OeUN=a6OTe1P3lY5l_RjO5ZJFhQR3LivCyMULmt1x-9K-ZeAWj3sOCu5z2AFjYL=6_a4XtpVIr50GNn=zruqR3veb351sa8Vs3kM9Qwh9NdIz=iD5QbuJlmeyHWU7OY9YSSGWE1T_Gq2deXnOcbVXaj4vmblDZ9f-S9Qbe8fYzCdyah6w0sR3-FVsSIxnOjWDMlHZ5PXWUIERfpANqdXO4Q3jSrYdYf-Vz5TyrpweWT55lP13IqbVf-N1DkJjX5sf2QYHclWs2SqdrqHTTdbrvnBtXxxQ1XfsUa1SCIoW9ZtE5dANi1N1AT5mPNcNfm113L6-KVaNV2w89Qs6y1kUEsHrz75J2vJ3OzKVAtE-N5e4eqfBKB0Q_Syv711tj55fXHmnyktaX5tMHBsGHcb0ovQZG7hhQOpVWurd8QN1zOU_fBhY8lDQxXiuaGvO9FDHiYJH8pFkZk0WvKdofmj5wDLJ9vyRcW8wBbmL0DtjUDUY11COuPqIi69kCB_1f4erBoxTX23GD4enFqEsfZpNd0NGklspVcrJ=SI4rrZ_fpL5wcO4C5vlaaQj45Q5_0rPua3DTVa6h1K0CuNmqoKh2FzEyloxf5XL4Tat_L4WEhfZiEQfZNVTm0fXZZX-bZEh9-1v8PUv6PdcSV1YZIxuS96oWChYU2MOLsmBuQQGPSp5K2rT_oIsO5ZeaDnxMQqGJ2a-lyq-LDI1Ir0AiRR4Nr=Ci5plA9x4d1QGKE20YJfzedEjKYHWSz_wCOU=pp82PlDFqaIUQuepfJJPvOVJ9X-O3NmePXe07UZSX-FVsFT7zIto27KTcqcCJIYwVY5s1dHVhX_TTMICCYQXOx=0D39JjRV1r0INSbNYY94XzU0e-iLraFb5=u4qhUffa3Rcs8svcoUuOhw=LVZ_YY4eaxNUflh9QvqBtK53kSOCPP95Wb5zLHu4rDsrDWP-bZKh02NQ62GHIe01yl_6vW6iIsdIvFXW8J_=BO0qLXA8-=QCaT0CZN-iAnNJch-0Qxvf9k4caMLaRwrvaLimSTSfVIkrpsMwl4JPzO_A-ms1-mB8xW_TYhI0UvhfUD8YWJLRGnPGFXMcL8e2yIhZF-eT06f5Nh82ZMdqZOdOS4UyfrpQz-7v8f2q9lQBmrfKIoYakHHMTrr6utnUkBIjsQS-Nk70uCspGA04KFzhjfvUuEckFTDtq6PDhLSlB=Omfbd1H8o9sRj51tdliLWJTkq44qTdEq-SlTPh8AKprG832PYVOytvfYw6G2X8U_pj7CcmkEaSrvQZ0LZPhYKaCbeOdDJaVXdeR8whQffs6AqFpcsitapVfGIAoTy8rDo=H=05dPUTJ1IGoM7YcSzq=UcFFwaZO_fYY6wYaUVSv_ebCSHOtA6Uc9Ta=eL2iaOG5pAdV93FmNUjSqZuCchR9Z2VlEA8CismxfX_-=fNhZCNaHe9cJVyK_ftDz8EPJP8SR0EdL3f7UuNzntY46y9ods2vNBFRnBpSA=zV_=hwXDBzMF8yN4bLslaGyfKkLmYIE7XVMw3=dneQj9I8dlnzEokDRIl-8-L-WxRCsFGlPDDbkaOssQtUSz8CQvc1EmJnEHJ7jHR5lbU-jklC=zLSJOxj0cb7_xq5RHOY05LhYjqB60=GOGcdYN17T7ZNbYuj5VDYZ7d6qZS4oOh2upu1ebfDHZN0qUu22V0=8ou7OsAIUcZLYNx4j8rTz6MPGoRPOSvJnqtxOiPbs3PrOZdkSFtE3zaQCjAiryx8YZ=0njEu0mGe=45ZvRvLjatS=mpXjNxdnSuCt_yXiknuDwfynndPNNoP2779FVveOE5Tm6NuW7Z5BBHa54Y-GGO-MuVs7y=5zh1dCaEfK_AXxPvcR1VYdY_CfPGV11IqMRAhQp4jdTR5SIwHXijmo69Pwkxnmm1hbY7RB6GC_5r_d56S4hXd6bFYeYlKsURnHq50rsQeSsOFMALIym8L78AXO7wpAApCyJXfsWbBUROaOAi4iFLffyqCimjj9OGaF4rDv_PuV5bMBsVf8rXdCu4E8umTj_XEOu3P91uDNJNDQdlPZ4EVb1TDT9X2xTIanKyUmzyRG1=zK0qZ_u_bqtEGBM9mSuamQhBZpwRCrHi0r5C1K-PXAZER3fnM8cAHqIx9lsirBPdbTQ0wn7QJ4uR4bcaXfmScDrh2RYAZMzZcyIaLPM5O3cJTUWqWRrt=EYxiTx05mmZ_d-AdZaXpWRNuH--L2R0zz_6dR3u5w4dUpHY8QS_T2tsZmwqi9BH5=W-H2Jj3Y_6rI_XsV_zPjHa6yxY=b-cUEWB5jFPYADCxLTrDs=TMDrQyEsCX71vWH4N0=3_fJt1LwVyOvhaecet8qyrT_M1-AQqXPetX1S5RsTT3W8JYaurTq-f10P9RnjZhjfuQlQu_YeTGF0e4ADJwa_xp-ux1uHij8lnGsWjN4HVjN2tTzH5QT27LFQWGT9Q_qsJzx4BWCy1e082wL6R8z9ozHrAVPw_48GqYOw8bE==8BfsbGVGKmYDR98axcn9rqu5P=ySMsDbx_bkW1q4l2uzQO5SQM3BPMeRePf1B3uVCGkmn4pY2=RpznewAPLGrGUDWJojflOokq0MWSHiRqP6Fxsz1woL1eq7wEEL8CxH0xshxVhR0T99JMYSTFYnoqPu8=bHUVTNFz5svZ_iNchVAOSPskMr7k2kk09BtT3cRyJ_6HjYp3fawpjTDAZQFmbqcUHB-tOwxWfXM-t8uHSSfyF8I_9E-y3QpUt4unAriw6PtBVec_149zS0ntTI6Ne3w6D6ksUSkR0cOQBd-WfH7k_F8K8_Tf0CVJPY7nxO34DRxw4FzX4OZx_lKvh=e9rzFJhUV2=WhI6qq1s4zA7s4Ty624AilOa8Vl6LFxhYmh02zUCkl4n2Ije4eIU4Wt23FDWKtYFyPxP06fM1oTlP2nmJAhjNhJEu1WufCzN09Alih0EkejyqYyRHqjFFZ0YNzUiRW1jvqQen1OR4M9fbZcnEOphz_42L657lEz2RFqbocT54ZTYFV6Qzo8tMY4RUfQm4kOLh3iQfboRTDHPo9SLdbOR8Z4yUK-BJrbpQodbBBZnLuPo=vv6pAl1I56cIbXaoZTm11k=iAJSbDL5rxZcNkwZbT5Sh09K0oB2nGBbXde50oxGLMXv1RWe-K0b6dB1Afce2pYwIbweRtxe4qsdtEK2ombB0ESeKa_uH6w7SWGNIkS0twaoYuyjIa4QMhDs1wULKak_177bCEure1pTVy=RBoXVhGIXn3AYPnzSCqiB=l4Q08dTZAfhBCmoTcdbB-BLI8hSTYrfYzPXL2pfRa5iFfaW-X4sXh=CnVolU7qnsfkOo5LwcnHM=1CMDLiDNJpnzUr6hFV13twKyRNnjMP=o0qam=IALpCQTXr4aad0np0jUanhf7zoC9fWXhmV5F=2zzRISU9djXkKJ1T-03tvSQCo5Hm8q-PBZpLFfq_RzK6G=l6_od-l-yqoX5HH-Wy7SLyXM4TyW=S55pp3R7BxejhhQBeEJyWzBvdPmwyYkpYS_B5yubd8-6Y6a4-N0bNRUGD7Ibl=ui5w_zxHN4bdE8TPY-_VHTsiA=h57E_yvHCIaQ6=9pRCLyye1ye__-zFA-UrOF1ZyziviozWFIltYw28F0hsduZLIMoCYzkt0GXdGXwLDN=9fMEuRw8jxjis31FGtxzvWEUEI02l0_YHCtrWfHssjUi8siAZQ8CZx-RhHG4xfeaPb2RLZ6u4nQ_TyuGYrJTBo9B9ESKj3qqr7fdIFx0hueNB5Jus2UymroWridK1S1d6YEKWjKvuA7oaJyCwmpPr9jvdSUeJSGVDAxOhK8MhBmIt3M0GJz-2z3asj_LjURpxLCmTn7wIENP=vDGB5FkYq2LWeYhlfJDGZ0=8HSp=Q5=CGANOEcz_pTyoAPtTx-rtaq-hLkoG6b8DuolFQkiTCveQRpvUWMLnkN1Iizk08bif5bO9rN9Hk9lRV=sSa1qmZQNLbDCi760vfGwKfsMy0PlIPEGykyulwxQD2qqbQ0fLiO7XpK2zhtDU0hEEwItNn1r5e8dpwl3Q9l5EIZdw9q0YnVqR1tOP_z3hhZeKj=Bd_3crtSpICA9DN=3w9PefJSmFefzvWM=1-mCC7LVwbRmSYoGCI_q4qotAPpjadTaKhO8nkVHFHbfbT1kV=PlsC0QntpT-3WQ-BekvlDBe7EwLe3XhPnMbHTixnn2laAJHJN_sCxAGChFZk6Yw7OhRJGNRV_ckGEwDxhXqDB_uCiivEywrnyHKT_SmGHi7X5SI6rjJJHW=cyk1k5M2fF9-JACKFYDSYd9X9Bdoa8dRSSH4Dac3qwl9F2HkuavHuwa8ddr9k-5YSwnFixO7Z=PQ66hQJw55TKOoJpRv4CLLJJCv0uA9uk2XDy5P1CGcMCOH0CZ4VWAr936dCiH-ZZH8trWh6WR=BF5lBFiaSoh93SKmKMqi3bC_h7VhSHtbq7_GMaVAiP5fGqeJQm8hikX85DCDAENvJakEMheoJrD9sAJB_cPOCD_kK4CVP3sR7BkNQyYVWTqdJSGH52VKm96DOj73JB3YUwNh6SFVzlvfXBrymM9XUZhkavhyenBtxDdwPqu_sBM2FaEyNB1E=zltapwfaDUNmJzw
Htc6j8njvn-A0:
RbqAwhwS6NcQtQYH-qmjTps
Htc6j8njvn-B:
-1js7w4
Htc6j8njvn-C:
AMCZeZOIAQAAOX0VKt1ay4ls5VAKByctdOopG2qtxQ-TQCUuNjtR7WmrlWT
Htc6j8njvn-D:
ABaAhIDBCKGFgQGAAYIQgISigaIAwBGzvpCzi_33wfY7Ue1pq5VkwAAAAAbNPOeAJXwY0ZkDxghjcKvIXBdgks
Htc6j8njvn-F:
A9qYk5OIAQAAv9rxISzpUoOYwcAKYKa1vwJtNCLQ7QpBXNhPmmjwRlSCgKXAQNqZQSuchRAwH9eCOfvosJeCA==
Htc6j8njvn-Z:
q

**Comment by loxeyer** [comment]
I found these params that tiktok added. but not same every times

**Comment by ViktorKravtsov** [comment]
> What worked for me was to also include X-Akamai-req id, the above comes from initial request to upload

@MrUnreal that 8-characters length string? Which you are getting from get request to https://www.tiktok.com/upload/ ???

**Comment by engagee** [comment]
> What worked for me was to also include X-Akamai-req id, the above comes from initial request to upload

Hey, @MrUnreal I tried, I get from the request in  

```
def uploadToTikTok(video, session):
    # 获取上传前的授权信息
    url = "https://www.tiktok.com/api/v1/video/upload/auth/"
    r = session.get(url)
    # header _store X-Akamai-Request-ID
    access_key = r.json()["video_token_v5"]["access_key_id"]
    secret_key = r.json()["video_token_v5"]["secret_acess_key"]
    session_token = r.json()["video_token_v5"]["session_token"]
    x_akamai_request_id = r.headers["X-Akamai-Request-ID"] #here

```
and in the header to send the post on f"https://{url_prefix}.tiktok.com/api/v1/web/project/post/?aid=1988"
```
headers = {
		# "X-Secsdk-Csrf-Token": x_csrf_token,
		'Host': f'{url_prefix}.tiktok.com',
		'X-Akamai-Request-ID': x_akamai_request_id, # tried with 'X-Akamai-Request-ID' and 'x-akamai-request-id'		 
                'authority': 'tiktok.com',
		'pragma': 'no-cache',
		'cache-control': 'no-cache',
		'sec-ch-ua': '"Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"',
		'accept': 'application/json, text/plain, */*',
		'content-type': 'application/json',
		'sec-ch-ua-mobile': '?0',
		'user-agent': UA,
		'sec-ch-ua-platform': '"macOS"',
		'origin': 'https://www.tiktok.com',
		'sec-fetch-site': 'same-site',
		'sec-fetch-mode': 'cors',
		'sec-fetch-dest': 'empty',
		'referer': 'https://www.tiktok.com/',    # network find vn tiktok, referer: https://us.tiktok.com/creator
		'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8'
	}
```
but didn't worked
how do you do to work?

**Comment by 546200350** [comment]
we need add x-bogus in the url.
i`m trying to find the calculate.
