### ISSUE TITLE
urllib3 unverified https request

### ISSUE THREAD

**Issue by MiguelRodriguezR** [546200350/TikTokUploder#37]
recently I am not caplabe to upload videos for this issue, does anyone has a clue what could be the solution ? 

```
Error: Command failed: python uploader.py -i "<SSID>" -p "...video.mp4" -t "🌳 Compartir Crece 🌱 " --tags  fyp foryoupage

...\anaconda3\lib\site-packages\urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'tos-awsuseast16-up.tiktokcdn.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "...\anaconda3\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "...\anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "...\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "...\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\uploader.py", line 117, in <module>
    uploadVideo(args.session_id, args.path, args.title, args.tags, args.users)
  File "...\uploader.py", line 96, in uploadVideo
    if r.json()["status_code"] == 0:
  File "...\Users\Miguel\anaconda3\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by MrUnreal** [comment]
Hey @MiguelRodriguezR that issue is not from unverified HTTPS request. TIktok added a few more flags that you need to pass in for the final step to go through. I will raise a PR soon once I am done testing

**Comment by loxeyer** [comment]
@MrUnreal How to raise a PR?

**Comment by MrUnreal** [comment]
fork - make your changes and raise pull request against the repo

**Comment by loxeyer** [comment]
i forked but not work and the error is :
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by MrUnreal** [comment]
I mean if you want to fix it you have to fix it first before trying ?

**Comment by loxeyer** [comment]
do you have fixed it ?

**Comment by MrUnreal** [comment]
still testing

**Comment by 546200350** [comment]
these params i have tryed before, it`s unuseful,so i remove it.
now, maybe the api checked these unuseful params.
sorry, I have been busy recently.

**Comment by loxeyer** [comment]
@546200350 tiktok加了一些参数，抓紧更新 buddy

**Comment by MiguelRodriguezR** [comment]
> Hey @MiguelRodriguezR that issue is not from unverified HTTPS request. TIktok added a few more flags that you need to pass in for the final step to go through. I will raise a PR soon once I am done testing

Thanks man, let me know if I can help in any way, maybe testing or something

**Comment by nhantamz** [comment]
bros, does Tiktok require X-Bogus param at last step? @MrUnreal @546200350

**Comment by craftfortress** [comment]
did anyone fix this? Id really appreciate an update sorry I havent had time to help

**Comment by MiguelRodriguezR** [comment]
@MrUnreal  @546200350 Hello guys is there any updates or solutions with this issue ?  I've been trying everithing but nothing seems to work

**Comment by nhantamz** [comment]
I can generate shape headers, xbogus but It does not work, the API still return empty string, lol. I dont know what is lacked.

**Comment by 546200350** [comment]
The key words is X-Bogus.
All of the algorithms are based on the Get on market, but we need  Post request.
I`m trying to fix it.

**Comment by 546200350** [comment]
i have resolved this problem, update the latest script and try again.
it`s work for me.
<img width="412" alt="image" src="https://github.com/546200350/TikTokUploder/assets/16091917/c5953b9f-ac62-41cb-9691-4d783d1d60f2">
