### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by cslop3r** [546200350/TikTokUploder#39]
Hello, can we add a music from Tiktok? Thanks for answering

**Comment by davidliaos** [comment]
desktop version doesnt allow it, so no since its a http get request.

**Comment by cslop3r** [comment]
> desktop version doesnt allow it, so no since its a http get request.

It isn't automatic?

**Comment by davidliaos** [comment]
what do you mean automatic?

you just cant add music because its a mobile feature.
you cant get cane sugar coca cola in america because they just dont offer it, you have to go to mexico for it.

**Comment by cslop3r** [comment]
> what do you mean automatic?
> 
> you just cant add music because its a mobile feature. you cant get cane sugar coca cola in america because they just dont offer it, you have to go to mexico for it.

Yes I understood for the music.
I mean by automatic if I let my script alone it will post the video, not by my hands

**Comment by XavierZambrano** [comment]
> desktop version doesnt allow it, so no since its a http get request.

In the past desktop version don't allow it, but now it allows it.

![image](https://github.com/546200350/TikTokUploder/assets/96162269/899f5678-34c0-4b50-aae9-98c1783c6cea)
![image](https://github.com/546200350/TikTokUploder/assets/96162269/87a1c1ac-fa64-46cf-9667-c4ca54925930)

In the payload exist the `"sinsgle_upload_param"`:
`"single_upload_param": [
{
  "video_param": {
    "text": "",
    "text_extra": [],
    "markup_text": "",
    "poster_delay": 0,
    "music_info": {
      "music_id": "7023061500537341954",
      "music_begin_time": 0,
      "music_end_time": 4966,
      "music_type": 1,
      "music_album": "",
      "music_author": "Imagine Dragons & JID & Arcane & League Of Legends",
      "music_title": "Enemy - from the series Arcane League of Legends",
      "music_selected_from": "web_page_search",
      "music_volume": "50",
      "origin_volume": "50"
    }
  },
  "batch_index": 0
}
]`


Note: If you don't see this feature in your desktop version TikTok can be testing it or not available for your region, I saw it from an account from Spain

**Comment by cslop3r** [comment]
Thanks a lot!!

> > desktop version doesnt allow it, so no since its a http get request.
> 
> In the past desktop version don't allow it, but now it allows it.
> 
> ![image](https://user-images.githubusercontent.com/96162269/250971177-899f5678-34c0-4b50-aae9-98c1783c6cea.png) ![image](https://user-images.githubusercontent.com/96162269/250971309-87a1c1ac-fa64-46cf-9667-c4ca54925930.png)
> 
> In the payload to `/api/v1/web/project/post/?aid=1988` exist the `"single_upload_param"`: `"single_upload_param": [ { "video_param": { "text": "", "text_extra": [], "markup_text": "", "poster_delay": 0, "music_info": { "music_id": "7023061500537341954", "music_begin_time": 0, "music_end_time": 4966, "music_type": 1, "music_album": "", "music_author": "Imagine Dragons & JID & Arcane & League Of Legends", "music_title": "Enemy - from the series Arcane League of Legends", "music_selected_from": "web_page_search", "music_volume": "50", "origin_volume": "50" } }, "batch_index": 0 } ]`
> 
> I don't test it at the moment, but in theory, we can do it.
> 
> Note: If you don't see this feature in your desktop version TikTok can be testing it or not available for your region, I saw it from an account from Spain

Thanks a lot!!

**Comment by JeroxGR** [comment]
> > desktop version doesnt allow it, so no since its a http get request.
> 
> In the past desktop version don't allow it, but now it allows it.
> 
> ![image](https://user-images.githubusercontent.com/96162269/250971177-899f5678-34c0-4b50-aae9-98c1783c6cea.png) ![image](https://user-images.githubusercontent.com/96162269/250971309-87a1c1ac-fa64-46cf-9667-c4ca54925930.png)
> 
> In the payload to `/api/v1/web/project/post/?aid=1988` exist the `"single_upload_param"`: `"single_upload_param": [ { "video_param": { "text": "", "text_extra": [], "markup_text": "", "poster_delay": 0, "music_info": { "music_id": "7023061500537341954", "music_begin_time": 0, "music_end_time": 4966, "music_type": 1, "music_album": "", "music_author": "Imagine Dragons & JID & Arcane & League Of Legends", "music_title": "Enemy - from the series Arcane League of Legends", "music_selected_from": "web_page_search", "music_volume": "50", "origin_volume": "50" } }, "batch_index": 0 } ]`
> 
> I don't test it at the moment, but in theory, we can do it.
> 
> Note: If you don't see this feature in your desktop version TikTok can be testing it or not available for your region, I saw it from an account from Spain

Hello! How can I get the data of the music ( title, album, duration... ) with only using the music id so i could pass it into the function
