### ISSUE TITLE
upload failed

### ISSUE THREAD

**Issue by deecancode** [546200350/TikTokUploder#41]
Please check the error below

![image](https://github.com/546200350/TikTokUploder/assets/102051369/696447ee-c415-45c1-8344-e2938e5a19a8)

**Comment by engagee** [comment]
its a problem to parse the json fo some response, run in debug mode and where breaks put the print() in response

**Comment by 546200350** [comment]
we need add x-bogus in the url.
i`m trying to find the calculate.

**Comment by 546200350** [comment]
#37
