### ISSUE TITLE
X-Bogus parameters work

### ISSUE THREAD

**Issue by titer18** [546200350/TikTokUploder#44]
X-Bogus Just like this [jiji262/douyin-downloader](https://github.com/jiji262/douyin-downloader/blob/5bf46f9736532668beafb4b051f69482fa8ab141/apiproxy/common/utils.py#L78)

**Comment by 546200350** [comment]
I've already seen it, it only supports the get request, we need a post request. 
Algorithm is not the same

**Comment by 546200350** [comment]
i have resolved this problem, update the latest script
