### ISSUE TITLE
Windows error cp1252 encoding

### ISSUE THREAD

**Issue by XavierZambrano** [546200350/TikTokUploder#47]
In Windows you can get an error like this:

`  File "C:\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position x-y`

This happens because per default use the cp1252 encoding, but you must use utf-8 so to fix it:

## TikTokUploader
uploader.py
replace this:
`	response = execjs.compile(open('./js/webssdk.js').read()).call('getSecretUrl', data)`
by this:
`	response = execjs.compile(open('./js/webssdk.js', encoding='utf-8').read()).call('getSecretUrl', data)`

## execjs
execjs > _external_runtime.py
replace this:

        def _exec_with_pipe(self, source):
            cmd = self._runtime._binary()

            p = None
            try:
                p = Popen(cmd, stdin=PIPE, stdout=PIPE, stderr=PIPE, cwd=self._cwd, universal_newlines=True)
                input = self._compile(source)
                if six.PY2:
                    input = input.encode(sys.getfilesystemencoding())
                stdoutdata, stderrdata = p.communicate(input=input)
                ret = p.wait()
            finally:
                del p

            self._fail_on_non_zero_status(ret, stdoutdata, stderrdata)
            return stdoutdata
by this:

        def _exec_with_pipe(self, source):
            cmd = self._runtime._binary()

            p = None
            try:
                p = Popen(cmd, stdin=PIPE, stdout=PIPE, stderr=PIPE, cwd=self._cwd, universal_newlines=True, encoding='utf-8')
                input = self._compile(source)
                if six.PY2:
                    input = input.encode(sys.getfilesystemencoding())
                stdoutdata, stderrdata = p.communicate(input=input)
                ret = p.wait()
            finally:
                del p

            self._fail_on_non_zero_status(ret, stdoutdata, stderrdata)
            return stdoutdata

**Comment by stevesajeev1** [comment]
I made a pull request #49 for this issue. @546200350
