### ISSUE TITLE
webssdk.js missing

### ISSUE THREAD

**Issue by cslop3r** [546200350/TikTokUploder#52]
Hello, I'm getting this error, if anyone could help please.
`  File "C:\Users\Nathan\Documents\RSL\uploader.py", line 81, in uploadVideo
    response = execjs.compile(open('./js/webssdk.js').read()).call('getSecretUrl', data)
                              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './js/webssdk.js'`

**Comment by 546200350** [comment]
update
now,we don`t need any js

**Comment by cslop3r** [comment]
thanks
