### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by cslop3r** [546200350/TikTokUploder#53]
Hello, I'm getting this new error. If anyone could help please.
`  File "C:\Users\Nathan\Documents\RSL\uploader.py", line 8, in <module>
    from .util import assertSuccess, printError, getTagsExtra, uploadToTikTok, log, getCreationId
ImportError: attempted relative import with no known parent package`

**Comment by stevesajeev1** [comment]
@cslop3r Try removing the . before util.

**Comment by cslop3r** [comment]
thanks!
