### ISSUE TITLE
Server is currently unavailable. Please try again later

### ISSUE THREAD

**Issue by ErinTomorri** [546200350/TikTokUploder#57]
Hey, I'm in Australia and the code works for a friend of mine in Canada, but I get this error when I run it. Is it something on TikToks backend that's not working or am I doing something wrong. When I click the link on chrome I get sent to a white page with this text "Server is currently unavailable. Please try again later". But when I click it on firefox its a white background.

============Start uploading video===========
C:\Users\\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'tos-awsuseast19-up.tiktokcdn.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
============Video uploaded successfully===========
============Publish failed===========
[-] An error occured while reaching https://www.tiktok.com/api/v1/web/project/post/
r = <Response [200]>
r.content = b'{"log_pb":{"impr_id":"202307100122452E3962ECA6B41833A22F"},"status_code":4,"status_msg":"Server is currently unavailable. Please try again later."}'
PS C:\Users\\Desktop\Tiktok Software\Tiktok-AI-main>

**Comment by nhantamz** [comment]
I think it's because the script sent the post command too early when Tiktok was still converting the video.

Another possibility is that the CDN region of tiktok US is US-TTP (check the request header on chrome dev tool) and not just ap-singapore or ap-useast.

**Comment by ErinTomorri** [comment]
> 

oh that makes sense I forgot cookies are brower specific thank you so much
