### ISSUE TITLE
No module named 'uploader'

### ISSUE THREAD

**Issue by cslop3r** [546200350/TikTokUploder#59]
Hello, I'm getting this error. Someone would have an idea how to solve it please?
`from uploader import uploadVideo
ModuleNotFoundError: No module named 'uploader'`
![image](https://github.com/546200350/TikTokUploder/assets/132304832/c2c64dbd-6232-463d-b77a-1c51eec8b8ce)

**Comment by UnMars** [comment]
Are you sure that you're running the commands inside the TikTokUploader folder ?

**Comment by cslop3r** [comment]
> Are you sure that you're running the commands inside the TikTokUploader folder ?

Thanks for your answer! If I do I'm getting another error:

`raceback (most recent call last):
  File "C:\Users\Nathan\Documents\RSL\index.py", line 36, in <module>
    from uploader import uploadVideo
  File "C:\Users\Nathan\Documents\RSL\uploader.py", line 7, in <module>
    from TikTokUploader.x_bogus_ import get_x_bogus
ModuleNotFoundError: No module named 'TikTokUploader'`
