### ISSUE TITLE
No module named 'TikTokUploader'

### ISSUE THREAD

**Issue by cslop3r** [546200350/TikTokUploder#63]
Hello, I'm getting this error. Could someone help me please?

`Traceback (most recent call last):
  File "C:\Users\Nathan\Documents\RSL\index.py", line 36, in <module>
    from uploader import uploadVideo
  File "C:\Users\Nathan\Documents\RSL\uploader.py", line 7, in <module>
    from TikTokUploader.x_bogus_ import get_x_bogus
ModuleNotFoundError: No module named 'TikTokUploader'`

**Comment by 546200350** [comment]
sorry for the md mistake. have a try
`
python3 ./TikTokUploader/uploader.py -i 7a9f3c5d8f6e4b2a1c9d8e7f6a5b4c3d -p my_video.mp4 -t "MY SUPER TITLE" --tags Funny Joke Fyp --users amazing
`

**Comment by cslop3r** [comment]
Thanks for your answer! What exactly have you changed? I use TikTok uploder inside my index.py script

**Comment by 546200350** [comment]
just the uploader path changed

**Comment by romanrsr** [comment]
Hi, I am receiving the same error, I have executed the code as is. What am I doing wrong? (I have tried both Linux and Windows)
![Captura2](https://github.com/546200350/TikTokUploder/assets/36116699/81df45ad-8701-4d9f-83f9-d56508a9c7b6)
