### ISSUE TITLE
Publish failed

### ISSUE THREAD

**Issue by quangkhjeu** [546200350/TikTokUploder#64]
An error occured while reaching https://us.tiktok.com/api/v1/web/project/post/
I've changed url_prefix="us" and url = 'https://us.tiktok.com/api/v1/web/project/post/' and it doesn't worked
![image](https://github.com/546200350/TikTokUploder/assets/26730825/5d23b440-0f5d-4dc6-bb02-bad220c62505)

**Comment by 546200350** [comment]
maybe you need change your net work. vpn

**Comment by quangkhjeu** [comment]
I use vps. After some tests, it worked perfectly but sometimes i got error like this

**Comment by 546200350** [comment]
Tiktok will check the net work,  mabe you can try using independent IP

**Comment by ErinTomorri** [comment]
> An error occured while reaching https://us.tiktok.com/api/v1/web/project/post/ I've changed url_prefix="us" and url = 'https://us.tiktok.com/api/v1/web/project/post/' and it doesn't worked ![image](https://user-images.githubusercontent.com/26730825/253211226-5d23b440-0f5d-4dc6-bb02-bad220c62505.png)

I had the same issue, make sure your sessionID is updated

**Comment by quangkhjeu** [comment]
> > An error occured while reaching https://us.tiktok.com/api/v1/web/project/post/ I've changed url_prefix="us" and url = 'https://us.tiktok.com/api/v1/web/project/post/' and it doesn't worked ![image](https://user-images.githubusercontent.com/26730825/253211226-5d23b440-0f5d-4dc6-bb02-bad220c62505.png)
> 
> I had the same issue, make sure your sessionID is updated

Do you know how often we have to update sessionID?

**Comment by Fabien-desablens** [comment]
if you disconnect from the device you got the sessionId, your sessionid will expire, that's what I know
