### ISSUE TITLE
Documentation apis called in source code

### ISSUE THREAD

**Issue by lavanphat** [546200350/TikTokUploder#65]
I found a Tiktok v1 api called in the source code.
```
/api/v1/web/project/create
/passport/web/account/info
...
```
I don't find document for this api in Tiktok document .Where can I find and read detailed documentation about these api ? Tks

**Comment by XavierZambrano** [comment]
You can upload the video manually while you have open dev tools in your browser, you can see its endpoints in the network section

No exist official documentation because is not the official API
