### ISSUE TITLE
Does anyone got zero views if upload via non US endpoint (www.tiktok.com/...) ? 

### ISSUE THREAD

**Issue by nhantamz** [546200350/TikTokUploder#66]
Hi bros,

recent days, all my non US accounts (www.tiktok.com/...) got zero views, US accounts with endpoint us.tiktok.com/... still got views.

I don't know what is wrong @_@ do u guys got same issue?

thanks.

**Comment by XavierZambrano** [comment]
It was happening to me (I only have one account in www prefix), but it was because my videos had no sound https://github.com/546200350/TikTokUploder/issues/61

**Comment by nhantamz** [comment]
I see that: 
- the video was uploaded by this script then watch on mobile: has sound, watch on web: no sound (1-2 days later, it will has sound)
- the video was uploaded via browser manually, watch both mobile and web, it has sound right after upload.

**Comment by quangkhjeu** [comment]
For me both got zero view

**Comment by XavierZambrano** [comment]
> I see that:
> 
> * the video was uploaded by this script then watch on mobile: has sound, watch on web: no sound (1-2 days later, it will has sound)
> * the video was uploaded via browser manually, watch both mobile and web, it has sound right after upload.

It's true, the videos later get sound, but 0 views

**Comment by XavierZambrano** [comment]
Do you continue with 0 views?

I continue with it, but if upload it manually I got views

**Comment by Fabien-desablens** [comment]
This is something I've noticed, when posting using desktop, even manually,  there are really few views on the videos, like 5 views in 10 minutes ,but using my phone I have like 200 views in 10 minutes. This is a Tiktok issue and this is really annoying.
So they need to fix this (maybe this is intentional ) or we need to find a way to post through the mobile thing not desktop, if any one have an idea

**Comment by Fabien-desablens** [comment]
As I said for me even when I post manually on the website, I have very very few views. It's a tiktok issue andI think this tiktok-uploder api works well though.

The official api allows you to post but you need to pass 2 audits.. : https://developers.tiktok.com/doc/content-sharing-guidelines#direct_post_api_-_developer_guidelines

**Comment by XavierZambrano** [comment]
> As I said for me even when I post manually on the website, I have very very few views. It's a tiktok issue and I think this tiktok-uploder api works as it should though.
> 
> The official api allows you to post but you need to pass 2 audits, one for your app to go in prod and an other tough one to access the "content posting api": https://developers.tiktok.com/doc/content-sharing-guidelines#direct_post_api_-_developer_guidelines

I don't got very few views, I got 0 views, 0 views always

**Comment by Fabien-desablens** [comment]
do u guys think it's possible to post as draft using the official api ? 
i'm not sure about that
tks

**Comment by nhantamz** [comment]
> [nhantamz](https://github.com/nhantamz) why is this issue closed? is this fixed??

no bro, still got 0, and there is new issue (some accounts got this issue, some account got no issue): video uploaded but not found in profile page =)) when I tried to access video with video ID I got from script, it said "Video currently unavailable"
