### ISSUE TITLE
I Got This Problem When Running The Code

### ISSUE THREAD

**Issue by satriaadiper** [546200350/TikTokUploder#67]
D:\tiktok-downloader>py uploader.py -i 2c9**************06171 -p (1).mp4 -t PART_1 --tags #FYP #Movie #Trending
[-] An error occured while reaching https://us.tiktok.com/api/v1/web/project/create/?creation_id=0mw6Pzm1UJlrkDb3RVbVA&type=1&aid=1988
[-] Please try to change the --url_server argument to the adapted prefix for your account

D:\tiktok-downloader>py uploader.py -i 2c9**************06171 -p (1).mp4 -t PART_1 --tags #FYP #Movie #Trending --url_server www
[-] An error occured while reaching https://www.tiktok.com/api/v1/web/project/create/?creation_id=6VnwfflAAmwgLRjmrpOYz&type=1&aid=1988
[-] Please try to change the --url_server argument to the adapted prefix for your account

first i use "us.tiktok.com" then i change to "www.tiktok.com", help me how to find prefix for my account

**Comment by 546200350** [comment]
maybe you can debug to find the real error, keyword 'KeyError'

**Comment by Fabien-desablens** [comment]
probably session id. Try to update your sessionid
