### ISSUE TITLE
Video uploads successfully yet doesn't appear on profile

### ISSUE THREAD

**Issue by andyscoming** [546200350/TikTokUploder#69]
Everything uploaded successfully with no errors, but the video doesn't show on my profile. I checked my sessionid was correct, and even logged in and out to reset it. Help?

**Comment by davidliaos** [comment]
you're probably scheduling them? when i schedule videos they just dont show until the schedule time when it uploads, try uploading without scheduling?

**Comment by andyscoming** [comment]
For anyone else with this issue, I had my "users" field blank. Whenever I added in a valid tiktok user it started showing up on my profile.

**Comment by lefranc137** [comment]
@andyscoming Hi mate i have the same problem, can you detail your solution plz
