### ISSUE TITLE
Not getting enough views

### ISSUE THREAD

**Issue by mtuub** [546200350/TikTokUploder#7]
Hii, I uploaded over 50 videos using this TikTokUploader, but I got maximum 50 views per video.

**Comment by 546200350** [comment]
This just a tool to upload videos 发自我的 iPhone在 2023年3月8日，下午6:30，mtuub ***@***.***> 写道：﻿
Hii, I uploaded over 50 videos using this TikTokUploader, but I got maximum 50 views per video.

**Comment by 546200350** [comment]
发自我的 iPhone在 2023年3月8日，下午6:30，mtuub ***@***.***> 写道：﻿
Hii, I uploaded over 50 videos using this TikTokUploader, but I got maximum 50 views per video.

**Comment by 546200350** [comment]
﻿发自我的 iPhone在 2023年3月8日，下午6:30，mtuub ***@***.***> 写道：﻿
Hii, I uploaded over 50 videos using this TikTokUploader, but I got maximum 50 views per video.
