### ISSUE TITLE
How to do line breaks ? 

### ISSUE THREAD

**Issue by Fabien-desablens** [546200350/TikTokUploder#71]
Hello, 
Tks for the Tiktok uploader, that's amazing.

but how can I do a line break in the description section ?
I've tried with \n and br but none of them work.

Here's my code: 
`
title = f"{generate_random_call_to_action()}\n{get_title_from_mp4(mp4_name)}" if mp4_name is not None else generate_random_call_to_action()`

and I modified the util.py :
`title +=  f"\n{verified_tag}"`

Thanks 

By the way a suggestion:  you should modify the comment "print(f"[-] Please try to change the --url_server argument to the adapted prefix for your account")" to "print(f"[-] Please try to change the --url_server argument to the adapted prefix for your account **or your session Id has changed**"). It took me some times to find out it was not due to the prefix but to the cookie lol.

**Comment by 546200350** [comment]
#72
