### ISSUE TITLE
How to specify to enable subtitles? 

### ISSUE THREAD

**Issue by craftfortress** [546200350/TikTokUploder#72]
I believe this is a flag - am I correct that it needs to be specified? 

Also: How to specify what filter to use and for how long? 

Thank you again everyone, excellent project! 

Big hugs

**Comment by XavierZambrano** [comment]
`uploadVideo()` does not support subtitles and filters

But you can add it, first manually upload a video with dev tools open in the Network section, you can find the necessary payload to add filters, and subtitles must be the same, with it data modify the code of `uploadVideo()` to add the necessary payload to works

Is the same case if you want to add music:
https://github.com/546200350/TikTokUploder/issues/39#issuecomment-1620611803

Related issue:
https://github.com/546200350/TikTokUploder/issues/40
