### ISSUE TITLE
Published but nothing on the profile

### ISSUE THREAD

**Issue by Fabien-desablens** [546200350/TikTokUploder#73]
Hello
It was working yesterday
but today my video is "published" but nothing on my profile, I updated the sessionid at least 5 times.
Any idea ?
           
```
                title = "test"
                tags = generate_tags(mp4_name)
                proxy=None
                file = file_path
                if uploadVideo(sessions[account], file, title, tags, proxy=proxy):
                    upload_success += 1
```

I print the response:

	if r.json()["status_code"] == 0:
		print(r.json()) 
{'extra': {'fatal_item_ids': [], 'logid': '202307261919357C66FA4FE681B4042741', 'now': 1690399176000}, 'info': {'projectID': '2307292421', 'status': 0, 'tasks': [{'batch_index': 0, 'item_id': '7260208650315156763', 'postID': 0, 'projectID': '0', 'taskID': 0}], 'type': 1, 'version': 1}, 'log_pb': {'impr_id': '202307261919357C66FA4FE681B4042741'}, 'status_code': 0, 'status_msg': 'success'}

Tks

**Comment by Fabien-desablens** [comment]
now it's uploading I don't get it few hours it was bugged and now it works fine..

**Comment by 546200350** [comment]
maybe it is limited by  tiktok
