### ISSUE TITLE
"status_code":2158,"status_msg":"You are posting too fast. Take a rest."

### ISSUE THREAD

**Issue by Fabien-desablens** [546200350/TikTokUploder#74]
```
⚫#TIKTOK: Video uploaded successfully
⚫#TIKTOK: Publish failed
[-] An error occured while reaching https://www.tiktok.com/api/v1/web/project/post/
r = <Response [200]>
r.content = b'{"log_pb":{"impr_id":"202307262222479C702F573DD39F012B5F"},"status_code":2158,"status_msg":"You are posting too fast. Take a rest."}'
```

I tried to add a sleep(60) before publishing but the error still occurs so I guess I've posted too frequently in a short period of time
If somebody know how often are we allowed to post it'd be appreciated
It's weird because I'm posting on two accounts at the same time and it only occurs on one account, the other one is okay.
Tks

**Comment by XavierZambrano** [comment]
¿Can you share the next points? at the moment no one share their upload limit

- Time between each video uploaded
- Number of videos uploaded
- Time between the first video and the last video uploaded

TikTok must restrict the number of videos and frequency in a elapse of time (days, weeks, etc), if the accounts share their IP, you should try with IP per account


https://github.com/546200350/TikTokUploder/issues/68

**Comment by Fabien-desablens** [comment]
I posted like more than 10 hours ago, few test like 3, I just tried again few minutes ago and I got the same error...

**Comment by Fabien-desablens** [comment]
today it's working . But the video is posted but no view.

**Comment by XavierZambrano** [comment]
> today it's working . The video is posted but no view.

https://github.com/546200350/TikTokUploder/issues/66
