### ISSUE TITLE
Scheduler doesn't actually schedule videos

### ISSUE THREAD

**Issue by hughesna** [546200350/TikTokUploder#75]
Appears to just immediately post the video regardless of the scheduled time

**Comment by hughesna** [comment]
think its bc the variable defaults to zero every time. I just made it a required param for the uploadVideo fxn and then removed some of the if statements regarding the schedule timing lower down and it worked.

**Comment by XavierZambrano** [comment]
if schedule_time and schedule_time - datetime.datetime.now().timestamp() > 900:  # 900s = 15min
		data["upload_param"]["schedule_time"] = schedule_time
if False, don't add the schedule_time and publish now

I think you refer to this piece of code, it replicates the requirement of TikTok web version

In the TikTok web version, the schedule must be as least 15 minutes in the future, and a maximum of 10 days, also the minutes in schedule_time must be multiple of 5 (this is not validated in the code)

¿Works schedule in 5 minutes, 10 minutes, and no multiple of 5? Yes, it works, but I think it is not normal, so they can more easily detect the uploader (I think this, but obviously idk)
