### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by cslop3r** [546200350/TikTokUploder#76]
Hello, is it possible to add titles like this?
![image](https://github.com/546200350/TikTokUploder/assets/132304832/0b9736b1-5587-4644-8485-16c064fd78fd)

**Comment by 546200350** [comment]
font image ?

**Comment by cslop3r** [comment]
I don't know how exactly it is called, it's a title visible in the video thumbsnail only

**Comment by 546200350** [comment]
mabe you need add in your video
