### ISSUE TITLE
Error when starting uploading

### ISSUE THREAD

**Issue by Zeffut** [546200350/TikTokUploder#78]
[-] An error occured while reaching https://us.tiktok.com/api/v1/web/project/create/?creation_id=KZSTu53KSK4txQhSC3dYX&type=1&aid=1988
[-] Please try to change the --url_server argument to the adapted prefix for your account

**Comment by Pxmme** [comment]
Try changing the URL server argument to "www" instead of "us". Did the trick for me.

**Comment by RonaldoNazo** [comment]
It is a problem with cookie "tt-target-idc"
Login using web browser ,and  check your cookies when logged in. 
This will show what region are servers located.
And try to add it on the uploader.py:
session.cookies.set("sessionid", session_id)
session.cookies.set("tt-target-idc","useast2a") #or useast1a as far as i have tried
