### ISSUE TITLE
403 error code

### ISSUE THREAD

**Issue by nhantamz** [546200350/TikTokUploder#9]
Hi bros,

I tried to upload via CLI and got issue like that, pls help. Thanks

![image](https://user-images.githubusercontent.com/63847256/224562648-2e01c298-08e1-48ee-a8f8-d0a057460616.png)

**Comment by 546200350** [comment]
maybe you need check the sessionId.
make sure it is correct

**Comment by seemayr** [comment]
Unfortunately I am facing the same issue, even when sessionId is correct.

**Comment by 546200350** [comment]
update the latest version
it have been resolved
