### ISSUE TITLE
NOT WORK!! ============Publish failed===========

### ISSUE THREAD

**Issue by MarcoLavoro** [546200350/TikTokUploder#91]
i GET THE ERROR:

C:\OFFLINEPROJECTS\BOTS\TikTokUploader4\TikTokUploder>python main.py --url_server www
============Start uploading video===========
C:\Users\carlo\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'tos-quic-gcpwaw1a.tiktokcdn.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
============Video uploaded successfully===========
============Publish failed===========
[-] An error occured while reaching https://www.tiktok.com/api/v1/web/project/post/
r = <Response [200]>
r.content = b'{"info":{},"log_pb":{"impr_id":"202406131312232406564616CB2F25A8A1"},"status_code":4,"status_msg":""}'

**Comment by NinhXNT** [comment]
Hi,
Have you managed to make it work yet? If yes, please share, i got same issue :(

**Comment by nalafei** [comment]
Hi,
Have you managed to make it work yet? If yes, please share, i got same issue :(

**Comment by awskmet** [comment]
I have the same issue

**Comment by zilton7** [comment]
any solutions? same issue

**Comment by marsafy1** [comment]
Hey @MarcoLavoro, @NinhXNT, @awskmet and @zilton7 
Kindly check this PR (https://github.com/546200350/TikTokUploder/pull/93), it fixed the issue for me...
Tell me how it goes :)
